"use client";
import ServiceProvider from "@/components/ServiceProvider";
import "./globals.css";
import { ApiReponseProvider } from "@/components/ApiResponseProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-[100vh]">
        <ApiReponseProvider>
          <ServiceProvider />
          {children}
        </ApiReponseProvider>
      </body>
    </html>
  );
}
