"use client";
import ServiceProvider from "@/components/ServiceProvider";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{fontFamily: 'san-serif', fontSize: '18px'}}>
      <body className="flex flex-col min-h-[100vh] overflow-y-scroll">
        <ServiceProvider />
        {children}
      </body>
    </html>
  );
}
