type TPinningService = {
  name: string;
  website: string;
  docsUrl: string;
  note: string;
  discontinued: boolean; // Whether a business is still running or not
  supportsMultiplePins: boolean; // Some services can take in an array of CIDs
  pathname?: string;
  ready: boolean; // Whether the service is supported by this app or not
  apiEndpoint: string;
  keyName: string; // key as in "key-value" for localStorage
  psaCompliant: boolean; // Wheher the service's APIs are fully compliant with the IPFS PSA requirements
  inputLabel: string;
  inputPlaceholder?: string;
};

export const PINNING_SERVICES: TPinningService[] = [
  {
    name: "Filebase.com",
    website: "https://filebase.com",
    docsUrl:
      "https://docs.filebase.com/api-documentation/ipfs-pinning-service-api",
    note: "Pinning APIs are available to paid customers",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://api.filebase.io/v1/ipfs",
    keyName: "filebaseAccessToken",
    psaCompliant: true,
    inputLabel: "Filebase Access Token",
  },
  {
    name: "NFT.Storage",
    website: "https://nft.storage",
    docsUrl: "https://nft.storage/docs/how-to/pinning-service",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://api.nft.storage",
    keyName: "nftStorageAccessToken",
    psaCompliant: true,
    inputLabel: "NFT.Storage API Key",
    inputPlaceholder: "eyJhbGciOi...",
  },
  {
    name: "4everland.org",
    website: "https://4everland.org",
    docsUrl:
      "https://docs.4everland.org/storage/4ever-pin/pinning-services-api",
    note: "",
    discontinued: false,
    supportsMultiplePins: true,
    ready: true,
    apiEndpoint: "https://api.4everland.dev",
    keyName: "4verlandAccessToken",
    psaCompliant: true,
    inputLabel: "4everland's Access Token",
  },
  {
    name: "Estuary.tech",
    website: "https://estuary.tech",
    docsUrl: "https://docs.estuary.tech/api/add-and-pin-object",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://api.estuary.tech/pinning",
    keyName: "estuaryAccessToken",
    psaCompliant: true,
    inputLabel: "Estuary's API Key",
  },
  {
    name: "Web3.storage",
    website: "https://web3.storage",
    docsUrl: "https://web3.storage/docs/how-tos/pinning-services-api/",
    note: "web3.storage's Pinning Service API is not to be used for ongoing production traffic, but rather for one-time migrations",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://api.web3.storage",
    keyName: "web3StorageAccessToken",
    psaCompliant: true,
    inputLabel: "Web3.Storage API Token",
    inputPlaceholder: "eyJhbGciOi...",
  },
  {
    name: "Infura.io",
    website: "https://infura.io",
    docsUrl: "https://docs.infura.io/infura/networks/ipfs/http-api-methods",
    note: "As of June 5th 2023, the pin api only accept cid and not its associate name/label",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/infura",
    keyName: "infuraAccessToken",
    psaCompliant: false,
    inputLabel: "Infura project ID & secret",
    inputPlaceholder: "<PROJECT_ID>:<PROJECT_SECRET>",
  },
  {
    name: "Dolpin.io",
    website: "https://dolpin.io",
    docsUrl: "https://docs.dolpin.io/pinning-api",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/dolpin",
    keyName: "dolpinAccessToken",
    psaCompliant: false,
    inputLabel: "Dolpin Acess Token",
    inputPlaceholder: "eyJhbGciOi...",
  },
  {
    name: "Chainsafe.io Storage",
    website: "https://storage.chainsafe.io",
    docsUrl: "https://docs.storage.chainsafe.io",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: false,
    apiEndpoint: "https://api.chainsafe.io/api/v1",
    keyName: "chainsafeApiKey",
    psaCompliant: true,
    inputLabel: "Chainsafe API Key",
  },
  {
    name: "Pinata.cloud",
    website: "https://pinata.cloud",
    docsUrl: "https://docs.pinata.cloud/pinata-api/pinning/pin-by-cid",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://api.pinata.cloud/psa",
    keyName: "pinataAccessToken",
    psaCompliant: true,
    inputLabel: "Pinata JWT",
    inputPlaceholder: "eyJhbGciOi...",
  },
  {
    name: "Crust.network",
    website: "https://crust.network",
    docsUrl: "https://wiki.crust.network/docs/en/buildFileStoringWithGWDemo",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "https://pin.crustcode.com/psa",
    keyName: "crustAccessToken",
    psaCompliant: true,
    inputLabel: "Crust Access Token",
  },
  {
    name: "Eternum.io",
    website: "https://eternum.io",
    docsUrl: "https://www.eternum.io/help/api",
    note: "",
    discontinued: true,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/eternum",
    keyName: "eternumAccessToken",
    psaCompliant: false,
    inputLabel: "Eternum Access Token",
  },
  {
    name: "Blockfrost.io",
    website: "https://blockfrost.io",
    docsUrl: "https://blockfrost.dev/docs/start-building/ipfs/",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/blockfrost",
    keyName: "blockforstProjectId",
    psaCompliant: false,
    inputLabel: "Blockfrost Project ID",
    inputPlaceholder: "ipfs...",
  },
  {
    name: "Spheron.network",
    website: "https://spheron.network",
    docsUrl: "https://docs.spheron.network/sdk/storage",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/spheron",
    keyName: "spheronAccessToken",
    psaCompliant: false,
    inputLabel: "Spheron Access Token",
    inputPlaceholder: "eyJhbGciOi...",
  },
  {
    name: "Scaleway.com",
    website: "https://sacleway.com",
    docsUrl: "https://scaleway.com/en/docs/labs/ipfs/api-cli/ipfs-operations",
    note: "",
    discontinued: false,
    supportsMultiplePins: false,
    ready: true,
    apiEndpoint: "/api/scaleway",
    keyName: "scalewayAuthToken",
    psaCompliant: false,
    inputLabel: "Scaleway Auth Token",
    inputPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  },
];
